name: "Build Test & Unit Test"

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "test/**"
  pull_request:
    paths:
      - "src/**"
      - "test/**"

jobs:
  run-test:
    name: "run tests"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: install dependencies
        run: |
          python3 -m pip install -e .
      - name: run tests
        id: tests
        # skip benchmark_test.py
        run: |
          python3 test/all_test.py --ignore benchmark
